```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, fig.width=10, fig.height=6, warning=F, message=F )
```


# Packages

```{r}
library( geojsonio )   # read shapefiles
library( sp )          # work with shapefiles
library( sf )          # work with shapefiles - simple features format
library( mclust )      # cluster analysis 
library( tmap )        # theme maps
library( ggplot2 )     # graphing 
library( ggthemes ) # nice formats for ggplots
library( dplyr )# data wrangling
library( pander )# formatting RMD tables
library( shiny )
library( wk )
library(shinyjs)
library(tidycensus) # Pulls census data
library(cartogram)# creates spatial maps w/ tract size bias reduction
library (maptools)# spatial object manipulation 
```

 Step 1: Select Your MSA

```{r}
crosswalk <- read.csv( "https://raw.githubusercontent.com/DS4PS/cpp-529-master/master/data/cbsatocountycrosswalk.csv",  stringsAsFactors=F, colClasses="character" )

# search for city names by strings, use the ^ anchor for "begins with" 

grep( "^CIN", crosswalk$msaname, value=TRUE ) 
```

```{r}
grep( "^CIN", crosswalk$msaname, value=TRUE ) 
```


```{r}
these.cin <- crosswalk$msaname == "CINCINNATI, OH-KY-IN"
these.fips <- crosswalk$fipscounty[ these.cin ]
these.fips <- na.omit( these.fips )
these.fips
head( these.fips ) %>% pander()
```

Step 2: Download a Shapefile with Population Data

To create a Dorling cartogram we need a shapefile and a population count. We can get both through the Census download that includes simple features.


```{r}
#You can get a Census API Key at: [https://api.census.gov/data/key_signup.html](https://api.census.gov/data/key_signup.html)



library(tidycensus)

census_api_key("0a6c09502c3be2c54109196047d6103d77442964")

key <- "0a6c09502c3be2c54109196047d6103d77442964"
census_api_key( key )

```

Step 1a Viewing the Data

```{r}
state.fips <- substr( these.fips, 1, 2 )
county.fips <- substr( these.fips, 3, 5 )

cbind( these.fips, state.fips, county.fips ) %>% pander()
```


```{r}
cin.pop1 <-
get_acs( geography = "tract", variables = "B01003_001",
         state = "39", county = county.fips[state.fips==39], geometry = TRUE ) %>% 
         select( GEOID, estimate ) %>%
         rename( POP=estimate )
```

```{r}
cin.pop2 <-
get_acs( geography = "tract", variables = "B01003_001",
         state = "18", county = county.fips[state.fips=="18"], geometry = TRUE ) %>% 
         select( GEOID, estimate ) %>%
         rename( POP=estimate )
```


```{r}
cin.pop3 <-
get_acs( geography = "tract", variables = "B01003_001",
         state = "21", county = county.fips[state.fips=="21"], geometry = TRUE ) %>% 
         select( GEOID, estimate ) %>%
         rename( POP=estimate )
```

```{r}
cin.pop <- rbind( cin.pop1, cin.pop2, cin.pop3 )
cin.pop
```
 
 Step 3: Add Census Data
```{r}
URL <- "https://github.com/DS4PS/cpp-529-master/raw/master/data/ltdb_std_2010_sample.rds"
census.dat <- readRDS(gzcon(url( URL )))

# can merge an sf object and data.frame
cin <- merge( cin.pop, census.dat, by.x="GEOID", by.y="tractid" )

# make sure there are no empty polygons
cin <- cin[ ! st_is_empty( cin ) , ]
```
 
Data Dictionary
 
```{r, echo=F}
# use dput( data.dictionary ) to create reproducible data frames for RMD files
data.dictionary <- 
structure(list(LABEL = c("pnhwht12", "pnhblk12", "phisp12", 
"pntv12", "pfb12", "polang12", "phs12", "pcol12", "punemp12", 
"pflabf12", "pprof12", "pmanuf12", "pvet12", "psemp12", "hinc12", 
"incpc12", "ppov12", "pown12", "pvac12", "pmulti12", "mrent12", 
"mhmval12", "p30old12", "p10yrs12", "p18und12", "p60up12", "p75up12", 
"pmar12", "pwds12", "pfhh12"), VARIABLE = c("Percent white, non-Hispanic", 
"Percent black, non-Hispanic", "Percent Hispanic", "Percent Native American race", 
"Percent foreign born", "Percent speaking other language at home, age 5 plus", 
"Percent with high school degree or less", "Percent with 4-year college degree or more", 
"Percent unemployed", "Percent female labor force participation", 
"Percent professional employees", "Percent manufacturing employees", 
"Percent veteran", "Percent self-employed", "Median HH income, total", 
"Per capita income", "Percent in poverty, total", "Percent owner-occupied units", 
"Percent vacant units", "Percent multi-family units", "Median rent", 
"Median home value", "Percent structures more than 30 years old", 
"Percent HH in neighborhood 10 years or less", "Percent 17 and under, total", 
"Percent 60 and older, total", "Percent 75 and older, total", 
"Percent currently married, not separated", "Percent widowed, divorced and separated", 
"Percent female-headed families with children")), class = "data.frame", row.names = c(NA, 
-31L))


data.dictionary %>% pander()
```
 
Step 4: Transform the Shapefile into A Dorling Cartogram

```{r}
# convert sf map object to an sp version
cin.sp <- as_Spatial( cin )

class( cin.sp )
```

```{r}
plot( cin.sp)
```
```{r}

library(rgdal)

# project map and remove empty tracts
cin.sp <- spTransform( cin.sp, CRS("+init=epsg:3395"))
cin.sp <- cin.sp[ cin.sp$POP != 0 & (! is.na( cin.sp$POP )) , ]


library( cartogram )  # spatial maps w/ tract size bias reduction
library( maptools )   # spatial object manipulation 
library( sf )         # 'simple features' flavor of shapefiles


# convert census tract polygons to dorling cartogram
# no idea why k=0.03 works, but it does - default is k=5
cin.sp$pop.w <- cin.sp$POP / 9000 # max(msp.sp$POP)   # standardizes it to max of 1.5
cin_dorling <- cartogram_dorling( x=cin.sp, weight="pop.w", k=0.03 )
plot( cin_dorling )

axis(side =1)
axis(side =2)
```

```{r}


library (tmap)

tmap_mode("view")
tm_basemap("Stamen.Watercolor")+
  tm_shape( cin_dorling ) + 
  tm_polygons( size="POP", col="hinc12", n=10, style="quantile", palette="PiYG" ) +
  tm_layout( "Cincinnati Area Cartogram", title.position=c("right", "top"))

```


```{r}

	
	# user-defined bounding box to move closer to subjects 
bb <- st_bbox( c( xmin =  -9435000, xmax = -9370000, 
                  ymax = 4685000, ymin = 4740000 ), 
               crs = st_crs("+init=epsg:3395"))

tm_shape( cin_dorling, bbox=bb ) + 
  tm_polygons( col="hinc12", title= "Median HH income, total", n=10, style="quantile", palette="PiYG" ) +
  tm_layout( "Cincinnati Area Cartogram", title.position=c("right","top") )

```


```{r}
# WRITE TO FILE 

library( geojsonio )

cin_dorling <- spTransform ( cin_dorling, CRS("+proj=longlat +datum=WGS84") )

geojson_write( cin_dorling, file="cin_dorling.geojson", geometry="polygon" )
```






